name: Deploy to Github pages
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Run deploy script
          run: |
            git config user.name "odala" && git config user.email "odalauten@gmail.com"
            npm ci
            npm run deploy